### ISSUE TITLE
Twitter integration?

### ISSUE THREAD

**Issue by maelle** [ropensci-archive/dvn#32]
:wave: @leeper! I see a "broken" Twitter integration cf https://github.com/ropensci/dvn/settings/installations could it be deleted? Or repaired?

**Comment by leeper** [comment]
This package is no longer functional with any modern Dataverse installation that I'm aware of it. It's on CRAN as a legacy. A modern replacement is here: https://github.com/IQSS/dataverse-client-r. I'd say we can delete anything and everything related to this repo.

**Comment by maelle** [comment]
ooooh good to know. if that's fine with you I'll give it the archiving treatment I've been giving other packages:

* Delete most info from the README except link to another package (because you could imagine people not seeing the archived status otherwise)

* Add an abandoned badge

* Add a "no entry" sign in the repo description and [DEPRECATED]

* Close all issues

* Archive

Are you ok with my doing it?

See other archived repos here https://github.com/ropensci?utf8=%E2%9C%93&q=&type=archived&language=

**Comment by sckott** [comment]
plan sounds good + archiving on cran 👍

**Comment by leeper** [comment]
Archived on CRAN now with a pointer to the new package. https://cran.r-project.org/web/packages/dvn/index.html

**Comment by maelle** [comment]
ok am going to do my job here, will be all clean and archived soon. thanks!

**Comment by maelle** [comment]
@leeper can you please give me your ok/make changes to the readme that I've shortened? Then I'll archive the repo.

**Comment by leeper** [comment]
@maelle Yep, please do as you suggested.
